config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#show'

  get :logout, to: "sessions#destroy", as: :logout
  get :login, to: "sessions#new", as: :login
  get :flyer, to: 'dashboard#flyer'
  get :impressum, to: 'dashboard#impressum'
  resources :sessions, only: [:create]
  resources :users

  resources :presets, only: [:index, :show, :update]
  resource :competitions, only: [:show, :edit, :update]
  resources :disciplines, only: [:index, :new, :create, :show, :destroy]
  resources :assessments do
    member { get :possible_associations }
  end
  resources :people do
    member do
      get :edit_assessment_requests
      get :statistic_suggestions
    end
    collection { get :without_statistics_id }
  end
  resources :teams do
    member do
      get :edit_assessment_requests
      get :statistic_suggestions
    end
    collection { get :without_statistics_id }
  end
  namespace :score do
    resource :list_factories, only: [:new, :create, :edit, :update, :destroy]
    resources :lists, only: [:show, :edit, :update, :index, :destroy] do
      member do
        get :move
        get :select_entity
        get "destroy_entity/:entry_id", action: :destroy_entity, as: :destroy_entity
        get :edit_times
      end
      resources :runs, only: [:edit, :update], param: :run
    end
    resources :results
    resources :competition_results, only: [:index]
  end

  namespace :fire_sport_statistics do
    resources :suggestions, only: [] do
      collection do
        get :people
        get :teams
      end
    end
  end

  namespace :certificates do
    resources :templates
    resources :lists, only: [:new, :create] do
      collection do
        post :export
      end
    end
  end

  namespace :imports do
    resources :configurations
  end

  namespace :series do
    resources :rounds, only: [:index, :show]
    resources :assessments, only: [:show]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action do
    redirect_to(presets_path) unless Competition.one.configured?
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def qrcode url
    RQRCode::QRCode.new(url, level: :h ).to_img.resize(200, 200).to_data_url
  end

  def hostname_url
    if decorated_competition.hostname.present?
      "http://#{decorated_competition.hostname}/"
    else
      ip_url
    end
  end

  def ip_url
    @ip_url ||= "http://#{Socket.ip_address_list.find {|a| a.ipv4?  && !a.ipv4_loopback? }.try(:ip_address)}/"
  end
end

app/views/dashboard/impressum.html.haml
.row
  .col-md-6
    = box "Impressum dieses Auftritts" do
      %p Für den Auftritt dieser Webseite ist der Veranstalter des Wettkampfes verantwortlich. Diese Seite ist nur im Intranet zu erreichen. Es werden neben dem Vor- und Zunamen keine persönlichen Daten gepeichert.
      %p Die Verfasser der Software übernehmen keine Garantie für Schäden jeglicher Art.
      %p
        Der Quellcode für den Wettkampf-Manger steht unter der AGPLv3 und kann unter
        = link_to("https://github.com/Feuerwehrsport/wettkampf-manager", "https://github.com/Feuerwehrsport/wettkampf-manager")
        heruntergeladen werden.

  .col-md-6
    = box "Über" do
      %p
        Der Wettkampf-Manager wird seit Frühjahr 2015 hauptsächlich von 
        = link_to("Georg Limbach", "http://www.georf.de")
        als quelloffene Software entwickelt. Ziel ist es, die Ergebnisberechnung von Feuerwehrsportwettkämpfen so einfach wie möglich zu gestalten.
      %p
        Als Basis wird das Framework Ruby on Rails 4.2 mit Ruby 2.1 benutzt. Weitere Informationen dazu finden sich auf
        = link_to("Feuerwehrsport-Statistik.de", "http://www.feuerwehrsport-statistik.de/wettkampf_manager")
        oder auf
        = link_to("Github", "https://github.com/Feuerwehrsport/wettkampf-manager")
        = "."
      %p
        Die aktuelle Entwicklung wird durch die 
        = link_to("Lichtbit GmbH", "http://lichtbit.com")
        aus Rostock unterstützt.
      %p 
        Im Vorfeld entwickelte
        = link_to("Daniel Grosche", "http://dgrosche.charlottenthal.de")
        seit 2004 die Vorversion dieses Wettkampf-Managers. Es handelte sich um ein Datenbank-Management-System, entwickelt mit Microsoft Visual FoxPro 6.0.

  .col-md-6
    = box "Lizenz" do
      = render 'license'
  .col-md-6
    = box "Lizenzen von Teilelementen" do
      %table.table.table-condensed
        - Gem.loaded_specs.each do |key, gem|
          %tr
            %th= gem.name
            %td= gem.version
            %td= gem.license

app/views/dashboard/show.html.haml
.row
  .col-md-7
    = box decorated_competition do |box|
      %h4= "#{l decorated_competition.date} - #{decorated_competition.place}"
      %table.table
        %tr
          %th
          %th Frauen
          %th Männer
        - if Person.count > 0
          %tr
            %th Angemeldete Wettkämpfer
            %th= Person.female.count
            %th= Person.male.count
        - if Team.count > 0
          %tr
            %th Angemeldete Mannschaften
            %th= Team.female.count
            %th= Team.male.count
  - if admin_logged_in?
    .col-md-5
      = box "Konfigurieren" do |box|
        = block_link_to "Wettkampf", edit_competitions_path
        = block_link_to "Passwort", edit_user_path(User.first)
        - if Imports::Configuration.possible?
          = block_link_to "Import von Feuerwehrsport-Statistik.de", imports_configurations_path
      = box "Aktionen" do |box|
        = block_link_to "Mannschaft hinzufügen", new_team_path
        = block_link_to "Startliste hinzufügen", new_score_list_factories_path
  .col-md-5
    = box link_to(hostname_url, hostname_url) do
      = image_tag qrcode(hostname_url)
      - if admin_logged_in?
        = block_link_to("Flyer anzeigen", format: :pdf, action: :flyer)
      - elsif !logged_in?
        = block_link_to("Anmelden", login_path)

  .col-md-6
    = box "Wettkampf-Manager" do |box|
      %p 
        Dieses Programm ist eine 
        %strong kostenlose und freie Software.
        Sie steht unter der Software-Lizenz
        %em AGPLv3
        und kann 
        = link_to("hier", "https://github.com/Feuerwehrsport/wettkampf-manager")
        heruntergeladen werden.
      - box.footer do
        = btn_link_to("Weitere Informationen", action: :impressum)