config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#show'

  get :logout, to: "sessions#destroy", as: :logout
  get :login, to: "sessions#new", as: :login
  get :flyer, to: 'dashboard#flyer'
  get :impressum, to: 'dashboard#impressum'
  resources :sessions, only: [:create]
  resources :users

  resources :presets, only: [:index, :show, :update]
  resource :competitions, only: [:show, :edit, :update]
  resources :disciplines, only: [:index, :new, :create, :show, :destroy]
  resources :assessments do
    member { get :possible_associations }
  end
  resources :people do
    member do
      get :edit_assessment_requests
      get :statistic_suggestions
    end
    collection { get :without_statistics_id }
  end
  resources :teams do
    member do
      get :edit_assessment_requests
      get :statistic_suggestions
    end
    collection { get :without_statistics_id }
  end
  namespace :score do
    resource :list_factories, only: [:new, :create, :edit, :update, :destroy]
    resources :lists, only: [:show, :edit, :update, :index, :destroy] do
      member do
        get :move
        get :select_entity
        get "destroy_entity/:entry_id", action: :destroy_entity, as: :destroy_entity
        get :edit_times
      end
      resources :runs, only: [:edit, :update], param: :run
    end
    resources :results
    resources :competition_results, only: [:index]
  end

  namespace :fire_sport_statistics do
    resources :suggestions, only: [] do
      collection do
        get :people
        get :teams
      end
    end
  end

  namespace :certificates do
    resources :templates
    resources :lists, only: [:new, :create] do
      collection do
        post :export
      end
    end
  end

  namespace :imports do
    resources :configurations
  end

  namespace :series do
    resources :rounds, only: [:index, :show]
    resources :assessments, only: [:show]
  end
end

app/models/fire_sport_statistics/person.rb
class FireSportStatistics::Person < ActiveRecord::Base
  enum gender: { female: 0, male: 1 }
  has_many :team_associations, class_name: 'FireSportStatistics::TeamAssociation'
  has_many :teams, through: :team_associations, class_name: 'FireSportStatistics::Team'
  has_one :person, class_name: '::Person', inverse_of: :fire_sport_statistics_person, foreign_key: :fire_sport_statistics_person_id

  validates :last_name, :first_name, :gender, presence: true

  scope :where_name_like, -> (name) do
    query = "%#{name.split("").join("%")}%"
    spelling_query = FireSportStatistics::PersonSpelling.where("(first_name || ' ' || last_name) LIKE ?", query).select(:person_id)
    where("(first_name || ' ' || last_name) LIKE ? OR id IN (#{spelling_query.to_sql})", query)
  end
  scope :order_by_gender, -> (gender) do
    order(gender: (gender == 'female') ? :asc : :desc)
  end
  scope :order_by_teams, -> (teams) do
    sql = teams.joins(:team_associations).where(fire_sport_statistics_team_associations: { person_id: arel_table[:id] }).to_sql
    order("EXISTS(#{sql}) DESC")
  end
  scope :gender, -> (gender) { where(gender: genders[gender]) }
  scope :for_person, -> (person) do
    where_name_like("#{person.first_name}#{person.last_name}").gender(person.gender)
  end
  scope :dummies, -> { where(dummy: true) }

  def self.dummy(person)
    find_or_create_by(last_name: person.last_name, first_name: person.first_name, gender: person.gender, dummy: true)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def full_name_changed?
    first_name_changed? || last_name_changed?
  end
end

app/models/imports/person.rb
class Imports::Person < Struct.new(:configuration, :data)
  def import
    team = configuration.teams.find { |team| team.foreign_key == data[:team_id] }.try(:competition_team)
    fssp = FireSportStatistics::Person.find_by(id: data[:statitics_person_id])
    @person = ::Person.create!(last_name: data[:last_name], first_name: data[:first_name], gender: data[:gender], team: team, fire_sport_statistics_person: fssp)
    data[:tag_names].each do |tag_name|
      tag = configuration.tags.find_by(target: :person, name: tag_name, use: true).try(:competition_tag)
      @person.tag_references.create!(tag: tag) if tag.present?
    end
    data[:assessment_participations].each do |participation|
      assessment = configuration.assessments.find_by(foreign_key: participation[:assessment_id]).try(:assessment)
      if assessment.present?
        AssessmentRequest.create!(
          entity: @person, 
          assessment: assessment, 
          assessment_type: participation[:assessment_type],
          single_competitor_order: participation[:single_competitor_order],
          group_competitor_order: participation[:group_competitor_order],
        )
      end
    end
  end
end

app/models/person.rb
class Person < CacheDependendRecord
  include Taggable

  belongs_to :team
  belongs_to :fire_sport_statistics_person, class_name: "FireSportStatistics::Person", inverse_of: :person
  has_many :requests, class_name: "AssessmentRequest", as: :entity, dependent: :destroy
  has_many :list_entries, class_name: "Score::ListEntry", as: :entity, dependent: :destroy
  has_many :requested_assessments, through: :requests, source: :assessment
  enum gender: { female: 0, male: 1 }
  before_save :assign_registration_order

  validates :last_name, :first_name, :gender, presence: true
  validate :validate_team_gender
  before_validation :strip_names

  accepts_nested_attributes_for :requests, allow_destroy: true

  default_scope { order(:gender, :last_name, :first_name) }
  scope :registration_order, -> () { reorder(:registration_order) }


  def request_for assessment
    requests.where(assessment: assessment).first
  end

  def fire_sport_statistics_person_with_dummy
    fire_sport_statistics_person.presence || FireSportStatistics::Person.dummy(self)
  end
 
  private

  def strip_names
    self.last_name = last_name.try(:strip)
    self.first_name = first_name.try(:strip)
  end

  def validate_team_gender
    errors.add(:team, :has_other_gender) if team.present? && team.gender != gender
  end

  def assign_registration_order
    if registration_order == 0 && team.present?
      self.registration_order = (team.people.maximum(:registration_order) || 0) + 1
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  implement_crud_actions
  before_action :assign_person_tags
  before_action :assign_resource_for_action, only: [:edit_assessment_requests, :statistic_suggestions]

  def edit_assessment_requests
  end

  def index
    super
    @female = @people.female.decorate
    @male = @people.male.decorate
    @without_statistics_id = @people.where(fire_sport_statistics_person_id: nil)
    page_title "Wettkämpfer"
  end

  def without_statistics_id
    @person_suggestions = base_collection.where(fire_sport_statistics_person_id: nil).map do |person|
      FireSportStatistics::PersonSuggestion.new(person).decorate
    end
  end

  def statistic_suggestions
    
  end

  protected

  def assign_person_tags
    @tags = PersonTag.all.decorate
  end

  def assign_resource_for_action
    assign_existing_resource
  end

  def after_create
    render 'edit_assessment_requests'
  end

  def build_resource
    instance = super
    instance.assign_attributes(team: team_from_param, gender: team_from_param.gender) if team_from_param.present?
    instance
  end

  def team_from_param
    @team_from_param ||= Team.find_by_id(params[:team])
  end

  def person_params
    params.require(:person).permit(:first_name, :last_name, :team_id, :gender, :fire_sport_statistics_person_id,
      :registration_order, :bib_number,
      requests_attributes: [:assessment_type, :_destroy, :assessment_id, :id, :group_competitor_order, :single_competitor_order],
      tag_references_attributes: [:id, :tag_id, :_destroy]
    )
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def specific_request(assessment) 
    request = @person.requests.find_or_initialize_by(assessment: assessment)
    request.assessment_type = :no_request unless request.persisted?
    request
  end

  def index_export_data(collection)
    assessments = Assessment.requestable_for(collection.first).map(&:decorate)
    headline = []
    headline.push('Nr.') if Competition.one.show_bib_numbers?
    headline.push('Nachname', 'Vorname', 'Mannschaft')
    @tags.each { |tag| headline.push(tag.to_s) }
    assessments.each { |assessment| headline.push(assessment.discipline.to_short) }
    data = [headline]
    
    collection.each do |person|
      line = []
      line.push(person.bib_number) if Competition.one.show_bib_numbers?
      line.push(person.last_name, person.first_name, person.team.numbered_shortcut_name)
      @tags.each { |tag| line.push(person.tags.include?(tag) ? 'X' : '') }
      assessments.each do |assessment|
        request = person.request_for(assessment.object)
        line.push(request.present? ? t("assessment_types.#{request.assessment_type}_short") : '')
      end
      data.push(line)
    end
    data
  end
end

app/views/people/_edit_assessment_requests.html.haml
= box @person, modal: true do |box|
  = simple_form_for @person, remote: true do |f|
    = f.error_notification
    - Assessment.requestable_for(@person).each do |assessment|
      .assessment-request
        = f.simple_fields_for :requests, @person.requests.find_or_initialize_by(assessment: assessment) do |g|
          = g.input :_destroy, as: :boolean, label: 'Teilnahme', input_html: { checked: g.object.persisted? }, checked_value: "0", unchecked_value: "1"
          = g.input :assessment_id, as: :hidden

          .row.edit-assesment-type
            .col-md-9
              = g.input :assessment_type, as: :select, collection: AssessmentRequest.assessment_types.keys, label: assessment.decorate, label_method: lambda { |type| t("assessment_types.#{type}") }
            .col-md-3.group-competitor-order
              = g.input :group_competitor_order
            .col-md-3.single-competitor-order
              = g.input :single_competitor_order
    .modal-footer
      = f.primary_button :submit, "Speichern"

app/views/people/_form.html.haml
= simple_form_for @person do |f|
  = box Person.model_name.human do |box|
    = f.error_notification
    = f.association :team, label_method: lambda { |team| team.decorate.numbered_name_with_gender }
    = f.input :first_name
    = f.input :last_name
    = f.input :gender, collection: [:male, :female]
    - if Competition.one.show_bib_numbers?
      = f.input :bib_number

    = render 'tag_form', f: f
    - box.footer do
      = cancel_link
      = f.primary_button :submit, "Speichern"

app/views/people/_index_table.html.haml
- if collection.count == 0
  .alert.alert-info Keine Einträge gefunden
- else
  %table.table.table-bordered.table-hover.table-condensed.people-index-table
    %tr
      - if Competition.one.show_bib_numbers?
        %th{ style: "width: 5%" } Nr.
      %th{ style: "width: 20%" } Nachname
      %th{ style: "width: 20%" } Vorname
      %th{ style: "width: 35%" } Mannschaft
      - @tags.each do |tag|
        %th{ style: "width: 5%" }= tag

      - assessments = Assessment.single_discipline(collection.first.gender).map(&:decorate)
      - assessments.each do |assessment|
        %th{ title: assessment }= discipline_image assessment.discipline
      - if admin_logged_in?
        %th
    - collection.each do |person|
      %tr
        - if Competition.one.show_bib_numbers?
          %td= person.bib_number
        %td= link_to person.last_name, person_path(person)
        %td= link_to person.first_name, person_path(person)
        %td= person.team
        - @tags.each do |tag|
          %td= person.tags.include?(tag) ? 'X' : ''
        - assessments.each do |assessment|
          - request = person.request_for(assessment.object).try(:decorate)
          - if request.present?
            %td{ title: "#{assessment}: #{request.type}" }= request.short_type
          - else
            %td
        - if admin_logged_in?
          %td= short_edit_link edit_assessment_requests_person_path(person), remote: true, class: "btn-xs", title: "Wertungsgruppen bearbeiten"

app/views/people/_modal_form.html.haml
= box Person.model_name.human, modal: true do |box|
  = simple_form_for @person, remote: true do |f|
    = f.error_notification
    .form-group.string
      %label.string.control-label{ for: "person_suggestion" } Schnelleingabe
      %input.string.form-control{ name: "person_suggestion", id: "person_suggestion", type: "text", data: { team_name: @person.try(:team).try(:name) }, autocomplete: :off }
    .suggestions-entries
      %table.table.table-hover.table-condensed
    .row
      - if PersonTag.all.present?
        .col-md-3
          = render 'tag_form', f: f
      .col-md-3
        = f.input :first_name
      .col-md-3
        = f.input :last_name
      .col-md-3
        = f.input :gender, collection: [:male, :female]
    .row
      - if @person.team.nil?
        .col-md-6
          = f.association :team, label_method: lambda { |team| team.decorate.numbered_name_with_gender }
      - else
        = f.hidden_field :team_id
      - if Competition.one.show_bib_numbers?
        .col-md-6
          = f.input :bib_number
    = f.hidden_field :fire_sport_statistics_person_id
    .modal-footer
      = f.primary_button :submit, "Speichern"

app/views/people/_statistic_suggestions.html.haml
= box @person, modal: true do |box|
  = simple_form_for @person, remote: true do |f|
    = f.error_notification
    .form-group.string
      %label.string.control-label{ for: "person_suggestion" } Name
      %input.string.form-control{ name: "person_suggestion", id: "person_suggestion", value: @person.to_s, type: "text", data: { team_name: @person.try(:team).try(:name), gender: @person.gender } }
    .suggestions-entries
      %table.table.table-hover.table-condensed
    .row.fire-sport-statistics-person
      .col-md-3.first-name= @person.fire_sport_statistics_person.try(:first_name)
      .col-md-3.last-name= @person.fire_sport_statistics_person.try(:last_name)
      .col-md-6.teams.small= @person.fire_sport_statistics_person.try(:team_list)
    = f.hidden_field :fire_sport_statistics_person_id
    .modal-footer
      = f.primary_button :submit, "Speichern"

app/views/people/_tag_form.html.haml
- @tags.each do |tag|
  - if @person.tag_references.find {|tag_ref| tag_ref.tag_id == tag.id }.present?
    = f.simple_fields_for :tag_references, @person.tag_references.find {|tag_ref| tag_ref.tag_id == tag.id } do |g|
      = g.input :_destroy, as: :boolean, label: tag.name, input_html: { checked: true }, checked_value: "0", unchecked_value: "1"
      = g.input :tag_id, as: :hidden
  - else
    = f.simple_fields_for :tag_references, @person.tag_references.find_or_initialize_by(tag: tag) do |g|
      = g.input :_destroy, as: :boolean, label: tag.name, input_html: { checked: false }, checked_value: "0", unchecked_value: "1"
      = g.input :tag_id, as: :hidden

app/views/people/edit_assessment_requests.js.erb
Modals.push("<%= j render partial: 'edit_assessment_requests' %>");

app/views/people/index.html.haml
.row
  .col-md-12.refreshable#people-index
    = box Person.model_name.human count: 0 do |box|
      - if admin_logged_in?
        - box.header do
          .pull-right
            = link_to "Hinzufügen", new_person_path, class: "btn btn-sm btn-info", remote: true
          .clearfix
        
        - if @without_statistics_id.present?
          .alert.alert-danger
            = "Es konnten zu #{@without_statistics_id.count} Wettkämpfern keine D-Cup-Ergebnisse gefunden wurden."
            = btn_link_to "Probleme ansehen", without_statistics_id_people_path


      %h4 Frauen
      = render "index_table", collection: @female
      %h4 Männer
      = render "index_table", collection: @male

      - box.footer do
        = btn_link_to "als PDF", format: :pdf
        = btn_link_to "als XLS", format: :xlsx
        - if admin_logged_in?
          = link_to "Hinzufügen", { action: :new }, class: "btn btn-sm btn-info", remote: true

app/views/people/new.js.erb
Modals.push("<%= j render partial: 'modal_form' %>");

app/views/people/show.html.haml
.row.refreshable#people-show
  .col-md-8
    = box(@person.full_name) do |box|
      %table.table
        %tr
          %th= @person.class.human_attribute_name :first_name
          %td= @person.first_name
        %tr
          %th= @person.class.human_attribute_name :last_name
          %td= @person.last_name
        %tr
          %th= @person.class.human_attribute_name :gender
          %td= @person.translated_gender

        - @tags.each do |tag|
          %tr
            %th= tag
            %td= @person.tags.include?(tag) ? 'Ja' : 'Nein'

        %tr
          %th= @person.class.human_attribute_name :team
          %td
            - if @person.team
              = link_to @person.team.name, team_path(@person.team)

      - if admin_logged_in?
        - box.footer do
          = btn_link_to "Löschen", { action: :destroy }, method: :delete, data: { confirm: 'Person wirklich löschen?' }
          = btn_link_to "Bearbeiten", action: :edit

  .col-md-8
    = box("Gewünschte #{Assessment.model_name.human count: 0}") do |box|
      %table.table
        - Assessment.requestable_for(@person).each do |assessment|
          - decorated_assessment = assessment.decorate
          %tr
            %th
              = discipline_image decorated_assessment.discipline
              = decorated_assessment
            %td
              - if @person.request_for(assessment).present?
                = t("assessment_types.#{@person.request_for(assessment).assessment_type}")
      - if admin_logged_in?
        - box.footer do
          = btn_link_to "Wertungsgruppen bearbeiten", { action: :edit_assessment_requests }, remote: true

app/views/people/statistic_suggestions.js.erb
Modals.push("<%= j render partial: 'statistic_suggestions' %>");

app/views/people/without_statistics_id.html.haml
- if admin_logged_in?
  .row
    .col-md-12.refreshable#without-statistics-id-index
      = box Person.model_name.human count: 0 do |box|
        %p Bei folgenden Einträgen konnten keine alten D-Cup-Ergebnisse zugeordnet werden. Dies kann zwei Ursachen haben:
        %ul
          %li Name wurde falsch geschrieben
          %li Erste Teilnahme beim D-Cup

        %table.table.table-bordered
          %tr
            %th Wettkampf-Name
            %th Online-Name
            %th Aktion
          - @person_suggestions.each do |suggestion|
            - if suggestion.match?
              %tr.success
                %td
                  = suggestion.person
                  %br
                  .small= suggestion.person.team
                %td
                  = suggestion.first
                  %br
                  .small= suggestion.first.team_list
                %td
                  = simple_form_for suggestion.person, remote: true do |f|
                    = f.hidden_field :fire_sport_statistics_person_id
                    = f.primary_button :submit, "Übernehmen", class: "btn-sm"

            - elsif suggestion.present?
              %tr.info
                %td
                  = suggestion.person
                  %br
                  .small= suggestion.person.team
                %td= "#{suggestion.suggestions.count} Vorschläge"
                %td= btn_link_to "Vorschlag auswählen", statistic_suggestions_person_path(suggestion.person), remote: true
            - else
              %tr.danger
                %td
                  = suggestion.person
                  %br
                  .small= suggestion.person.team
                %td Keine Vorschläge
                %td= btn_link_to "Vorschlag suchen", statistic_suggestions_person_path(suggestion.person), remote: true