config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#show'

  get :logout, to: "sessions#destroy", as: :logout
  get :login, to: "sessions#new", as: :login
  get :flyer, to: 'dashboard#flyer'
  get :impressum, to: 'dashboard#impressum'
  resources :sessions, only: [:create]
  resources :users

  resources :presets, only: [:index, :show, :update]
  resource :competitions, only: [:show, :edit, :update]
  resources :disciplines, only: [:index, :new, :create, :show, :destroy]
  resources :assessments do
    member { get :possible_associations }
  end
  resources :people do
    member do
      get :edit_assessment_requests
      get :statistic_suggestions
    end
    collection { get :without_statistics_id }
  end
  resources :teams do
    member do
      get :edit_assessment_requests
      get :statistic_suggestions
    end
    collection { get :without_statistics_id }
  end
  namespace :score do
    resource :list_factories, only: [:new, :create, :edit, :update, :destroy]
    resources :lists, only: [:show, :edit, :update, :index, :destroy] do
      member do
        get :move
        get :select_entity
        get "destroy_entity/:entry_id", action: :destroy_entity, as: :destroy_entity
        get :edit_times
      end
      resources :runs, only: [:edit, :update], param: :run
    end
    resources :results
    resources :competition_results, only: [:index]
  end

  namespace :fire_sport_statistics do
    resources :suggestions, only: [] do
      collection do
        get :people
        get :teams
      end
    end
  end

  namespace :certificates do
    resources :templates
    resources :lists, only: [:new, :create] do
      collection do
        post :export
      end
    end
  end

  namespace :imports do
    resources :configurations
  end

  namespace :series do
    resources :rounds, only: [:index, :show]
    resources :assessments, only: [:show]
  end
end

app/models/certificates/list.rb
class Certificates::List
  extend ActiveModel::Naming
  extend ActiveModel::Translation
  include ActiveModel::Model
  include ActiveModel::Validations
  include ActiveRecord::AttributeAssignment
  include ActiveRecord::Callbacks
  include Draper::Decoratable
  attr_accessor :template_id, :score_result_id, :score_result, :image

  validates :template, :score_result, presence: true

  def template
    Certificates::Template.find_by_id(template_id)
  end

  def score_result
    Score::Result.find_by_id(score_result_id)
  end

  def save
    valid?
  end

  def pages
    page_text_values = []

    result.rows.map(&:decorate).each do |row|
      if row.is_a?(Score::DoubleEventResultRow)
        result_entry = row.sum_result_entry
      else
        result_entry = row.best_result_entry
      end

      page_text_values.push(
        team_name: row.entity,
        person_name: row.entity,
        time_long: result_entry.long_human_time(seconds: 'Sekunden') ,
        time_short:  result_entry.long_human_time(seconds: 's'),
        rank: "#{place_for_row row}.",
        assessment: assessment,
        assessment_with_gender: assessment,
        gender: assessment.gender,
        date: Competition.one.date,
        place: Competition.one.place,
        competition_name: Competition.name,
      )
    end
  end
end

app/models/concerns/score/list_factory_defaults.rb
module Score::ListFactoryDefaults
  def possible_assessments
    Assessment.where(discipline: discipline)
  end

  def possible_results
    Score::Result.where(id: assessments.joins(:results).pluck("score_results.id"))
  end

  def possible_before_results
    Score::Result.where(id: assessments.joins(:results).pluck("score_results.id"))
  end

  def possible_before_lists
    Score::List.where(id: assessments.joins(:lists).pluck("score_lists.id"))
  end

  def default_name
    name.presence || begin
      if !discipline.is_a?(Disciplines::FireRelay)
        "#{default_main_name} - Lauf #{default_run}"
      else
        default_main_name
      end
    end
  end

  def default_shortcut
    shortcut.presence || begin
      if !discipline.is_a?(Disciplines::FireRelay)
        "Lauf #{default_run}"
      else
        'Lauf'
      end
    end
  end

  def default_track_count
    track_count.presence || 2
  end

  def default_results
    results.presence || possible_results
  end

  def default_type
    type.presence || possible_types.first
  end

  def default_before_list
    before_list.presence || possible_before_lists.first
  end

  def default_before_result
    before_result.presence || possible_before_results.first
  end

  def default_best_count
    best_count.presence || 30
  end

  protected

  def default_main_name
    @default_main_name ||= assessments.count == 1 ? assessments.first.decorate.to_s : discipline.decorate.to_s
  end

  def default_run
    run = 1
    loop do
      break if Score::List.where(name: "#{default_main_name} - Lauf #{run}").blank?
      run += 1
    end
    run
  end
end

app/models/concerns/score/result_entry_support.rb
module Score::ResultEntrySupport
  INVALID_TIME = 99999999
  ENTRY_STATUS = [:waiting, :valid, :invalid, :no_run]
    
  def second_time
    return "" if time.blank? || time == 0
    seconds = time.to_i / 100
    millis = time.to_i % 100
    "#{seconds},#{sprintf('%02d', millis)}"
  end

  def edit_second_time
    second_time.gsub(',', '.')
  end

  def edit_second_time=(new_second_time)
    self.second_time = new_second_time
  end

  def second_time=(new_second_time)
    if result = new_second_time.match(/^(\d+):(\d{1,2})[,.](\d{1,2})$/)
      self.time = result[1].to_i*6000 + result[2].to_i*100 + result[3].to_i
    elsif result = new_second_time.match(/^(\d{1,4})[,.](\d)$/)
      self.time = result[1].to_i*100 + (result[2].to_i * 10)
    elsif result = new_second_time.match(/^(\d{1,3})[,.](\d\d)$/)
      self.time = result[1].to_i*100 + result[2].to_i
    else
      self.time = new_second_time.to_i*100
    end
  end

  def time_with_valid_calculation=(time)
    self.time = time
    self.result_valid = time.present? && time < INVALID_TIME
  end

  def result_valid=(valid)
    self.result_type = valid ? :valid : :invalid
  end

  def result_type
    super.try(:to_sym)
  end

  def result_valid?
    result_type == :valid
  end

  def result_waiting?
    result_type == :waiting
  end

  def result_invalid?
    result_type == :invalid
  end

  def result_no_run?
    result_type == :no_run
  end

  def compare_time
    result_valid? && time < INVALID_TIME ? time : INVALID_TIME
  end

  def <=>(other)
    compare_time <=> other.compare_time
  end
end

app/models/score.rb
module Score
  def self.table_name_prefix
    'score_'
  end
end

app/models/score/assessment_result.rb
class Score::AssessmentResult < Struct.new(:points, :assessment, :result_entry, :team, :row)
  delegate :discipline, to: :assessment
end

app/models/score/competition_result.rb
class Score::CompetitionResult < CacheDependendRecord
  include Genderable

  has_many :assessments, foreign_key: :score_competition_result_id
  has_many :results, -> { where(score_results: { group_assessment: true }) }, through: :assessments, class_name: 'Score::Result'

  validates :result_type, presence: true

  def rows
    @rows ||= result_type.present? ? send(result_type) : []
  end

  def result_type
    super.presence || Competition.result_type
  end

  def self.result_types
    {
      dcup: "D-Cup",
      places_to_points: "Plätze zu Punkte",
    }
  end

  private

  def for_results
    results.each do |result|
      discipline = result.assessment.discipline
      if discipline.single_discipline?
        result_rows = Score::GroupResult.new(result).rows
      else
        result_rows = result.group_result_rows
      end


      ranks = {}
      result_rows.each do |row|
        result_rows.each_with_index do |rank_row, rank|
          if 0 == (row <=> rank_row)
            ranks[row] = (rank + 1)
            break
          end
        end
      end

      yield result, result_rows, ranks
    end
  end

  def dcup
    teams = {}
    for_results do |result, result_rows, ranks|
      points = 11
      result_rows.each do |row|

        rank = ranks[row]
        double_rank_count = ranks.values.select { |v| v == rank }.count - 1
        points = [(11 - ranks[row] - double_rank_count), 0].max
        points = 0 unless row.competition_result_valid?

        assessment_result = Score::AssessmentResult.new(points, result.assessment, row.result_entry, row.entity, row)
        teams[row.entity.id] ||= Score::CompetitionResultRow.new(self, row.entity)
        teams[row.entity.id].add_assessment_result(assessment_result)
      end
    end
    teams.values.sort
  end

  def places_to_points
    teams = {}
    for_results do |result, result_rows, ranks|
      result_rows.each do |row|
        points = ranks[row]
        assessment_result = Score::AssessmentResult.new(points, result.assessment, row.result_entry, row.entity, row)
        teams[row.entity.id] ||= Score::CompetitionResultRow.new(self, row.entity)
        teams[row.entity.id].add_assessment_result(assessment_result)
      end
    end
    for_results do |result, result_rows, ranks|
      next if result_rows.empty?
      points = ranks.values.max + 1
      teams.keys.each do |team_id|
        if teams[team_id].assessment_result_from(result.assessment).blank?
          assessment_result = Score::AssessmentResult.new(points, result.assessment, Score::ResultEntry.invalid, Team.find(team_id), nil)
          teams[team_id].add_assessment_result(assessment_result)
        end
      end
    end
    teams.values.sort
  end
end

app/models/score/competition_result_row.rb
class Score::CompetitionResultRow < Struct.new(:competition_result, :team)
  include Draper::Decoratable
  attr_reader :assessment_results

  def add_assessment_result(assessment_result)
    @assessment_results ||= []
    @assessment_results.push(assessment_result)
  end

  def points
    @assessment_results.map(&:points).sum
  end

  def assessment_result_from(assessment)
    @assessment_results.select { |result| result.assessment == assessment }.first
  end

  def fire_attack_result_entry
    @assessment_results.select do |result|
      result.discipline.is_a?(Disciplines::FireAttack)
    end.first.try(:result_entry) || Score::ResultEntry.new(result_valid: false)
  end

  def <=>(other)
    competition_result.result_type.nil? ? 0 : send(:"#{competition_result.result_type}_compare", other)
  end

  private

  def dcup_compare(other)
    compare = other.points <=> points
    return fire_attack_result_entry <=> other.fire_attack_result_entry if compare == 0
    compare
  end

  def places_to_points_compare(other)
    compare = points <=> other.points
    return fire_attack_result_entry <=> other.fire_attack_result_entry if compare == 0
    compare
  end
end

app/models/score/double_event_result.rb
class Score::DoubleEventResult < Score::Result
  has_many :results, class_name: 'Score::Result'

  def generate_rows
    rows = {}
    results.each do |result|
      result.rows.select(&:valid?).each do |result_row|
        if rows[result_row.entity.id].nil?
          rows[result_row.entity.id] = Score::DoubleEventResultRow.new(result_row.entity)
        end
        rows[result_row.entity.id].add_result_row(result_row)
      end
    end
    @out_of_competition_rows = []
    rows.values.select { |row| row.result_rows.count == results.count }
  end
end

app/models/score/double_event_result_row.rb
class Score::DoubleEventResultRow < Struct.new(:entity)
  include Draper::Decoratable
  attr_reader :result_rows

  def add_result_row(result_row)
    @result_rows ||= []
    @result_rows.push(result_row)
  end

  def sum_result_entry
    @sum_result_entry ||= Score::ResultEntry.new(time_with_valid_calculation: result_rows.map(&:best_result_entry).map(&:compare_time).sum)
  end

  def result_entry
    sum_result_entry
  end

  def result_entry_from(result)
    result_rows.select { |row| row.result == result }.map(&:best_result_entry).first
  end

  def <=>(other)
    compare = sum_result_entry <=> other.sum_result_entry
    return compare if compare != 0
    if entity.gender.to_s == "female"
      compare = obstacle_course_time <=> other.obstacle_course_time
      return compare if compare != 0
      climbing_hook_ladder_time <=> other.climbing_hook_ladder_time
    else
      compare = climbing_hook_ladder_time <=> other.climbing_hook_ladder_time
      return compare if compare != 0
      obstacle_course_time <=> other.obstacle_course_time
    end
  end

  def result_rows
    @result_rows.presence || []
  end

  protected

  def climbing_hook_ladder_time
    time_by_discipline(Disciplines::ClimbingHookLadder)
  end
  
  def obstacle_course_time
    time_by_discipline(Disciplines::ObstacleCourse)
  end

  def time_by_discipline(discipline_class)
    result_rows.find { |row| row.result.assessment.discipline.is_a?(discipline_class) }.try(:best_result_entry)
  end
end

app/models/score/group_result.rb
class Score::GroupResult < Struct.new(:result)
  def rows
    @sorted ||= calculated_rows.sort
  end

  def calculated_rows
    team_scores = {}
    competition = Competition.one
    run_count = competition.group_run_count
    score_count = competition.group_score_count

    run_count = result.group_run_count if result.group_run_count.present?
    score_count = result.group_score_count if result.group_score_count.present?

    result.rows.each do |result_row|
      next unless result_row.list_entries.first.group_competitor?
      next if result_row.entity.team.nil?

      if team_scores[result_row.entity.team].nil?
        team_scores[result_row.entity.team] = Score::GroupResultRow.new(result_row.entity.team, score_count, run_count)
      end
      team_scores[result_row.entity.team].add_result_row(result_row)
    end
    team_scores.values.sort
  end
end

app/models/score/group_result_row.rb
class Score::GroupResultRow < Struct.new(:team, :score_count, :run_count)
  include Draper::Decoratable

  def entity
    team
  end

  def add_result_row(result_row)
    @result_rows ||= []
    @result_rows.push(result_row)
  end

  def result_entry
    calculate
    Score::ResultEntry.new(time_with_valid_calculation: @time)
  end

  def rows_in
    calculate
    @rows_in
  end

  def rows_out
    calculate
    @rows_out
  end

  def valid?
    result_entry.result_valid?
  end

  # Zeigt an, ob es generell gültig ist
  # Ungültig, wenn zu viele oder zu wenige gestartet sind
  def competition_result_valid?
    @result_rows.count >= score_count && @result_rows.count <= run_count
  end

  def valid_compare
    competition_result_valid? ? 0 : 1
  end

  def <=>(other)
    compare = valid_compare <=> other.valid_compare
    compare == 0 ? result_entry <=> other.result_entry : compare
  end

  protected

  def calculate
    return if @calculated
    @time = 0
    @rows_in = []
    @rows_out = []
    @result_rows ||= []
    if !competition_result_valid?
      @time = nil
      return
    end
    queue = @result_rows.sort
    (1..score_count).each do
      current = queue.shift
      if current.nil? || !current.best_result_entry.result_valid?
        @time = nil
      else
        @time += current.best_result_entry.time
      end
      @rows_in.push(current) if current.present?
    end
    (score_count + 1..run_count).each do
      current = queue.shift
      @rows_out.push(current) if current.present?
    end
    @calculated = true
  end
end

app/models/score/list.rb
class Score::List < CacheDependendRecord
  include Taggable

  has_many :list_assessments, dependent: :destroy
  has_many :assessments, through: :list_assessments
  has_many :result_lists, dependent: :destroy
  has_many :results, through: :result_lists
  has_many :entries, -> { order(:run).order(:track) }, class_name: "Score::ListEntry", dependent: :destroy

  default_scope { order(:name) }

  validates :name, :assessments, :track_count, :shortcut, presence: true
  validates :track_count, numericality: { greater_than: 0 }
  validates :shortcut, length: { maximum: 8 }
  accepts_nested_attributes_for :entries, allow_destroy: true

  def next_free_track
    last_entry = entries.last
    run = last_entry.try(:run) || 1
    track = last_entry.try(:track) || 1
    track += 1
    if track > track_count
      track = 1
      run += 1
    end
    [run, track]
  end
end

app/models/score/list_assessment.rb
class Score::ListAssessment < CacheDependendRecord
  belongs_to :assessment
  belongs_to :list
end

app/models/score/list_entry.rb
class Score::ListEntry < CacheDependendRecord
  include Score::ResultEntrySupport

  belongs_to :list, class_name: 'Score::List'
  belongs_to :entity, polymorphic: true
  belongs_to :assessment
  
  enum assessment_type: { group_competitor: 0, single_competitor: 1, out_of_competition: 2 }

  validates :list, :entity, :track, :run, :assessment_type, :assessment, presence: true
  validates :track, :run, numericality: { greater_than: 0 }
  validates :track, numericality: { less_than_or_equal_to: :track_count }

  delegate :track_count, to: :list

  scope :result_valid, -> { where(result_type: :valid) }
  scope :not_waiting, -> { where.not(result_type: :waiting) }

  def self.insert_random_values
    where(result_type: :waiting).each {|l| l.update!(time_with_valid_calculation: 1900 + rand(0..400)) }
  end
end

app/models/score/list_factories/lottery_number.rb
class Score::ListFactories::LotteryNumber < Score::ListFactory
  def self.generator_possible?(discipline)
    discipline.group_discipline? && Competition.one.lottery_numbers? && !discipline.is_a?(Disciplines::FireRelay)
  end

  protected

  def perform_rows
    assessment_requests
  end
end

app/models/score/list_factories/simple.rb
class Score::ListFactories::Simple < Score::ListFactory
  protected

  def perform_rows
    assessment_requests.shuffle
  end
end

app/views/score/lists/_destroy_entity.html.haml
= box "Teilnehmer aus Liste entfernen", modal: true do |box|
  = simple_form_for @score_list, remote: true do |f|
    = f.error_notification
    = f.simple_fields_for :entries, @score_list.entries.where(id: params[:entry_id]) do |g|
      = g.input :_destroy, as: :hidden, input_html: { value: "1" }
      = "Teilnehmer: #{g.object.entity.decorate}"
    .modal-footer
      = f.primary_button :submit, "Entfernen"

app/views/score/lists/_form.html.haml
= simple_form_for @score_list do |f|
  = box @score_list do |box|
    = f.error_notification
    = f.input :name
    = f.input :shortcut, input_html: { maxlength: 8 }
    = f.input :date, as: :string
    = f.association :results, collection: Score::Result.all, as: :check_boxes
    = render 'tag_form', f: f
    - box.footer do
      = cancel_link
      = f.primary_button :submit, "Speichern"

app/views/score/lists/_list_entry.html.haml
%tr{ list_entry_options(track, entry) }
  %td.run
    - if track == 1
      = run
  %th.track= track
  - if single_discipline?
    - if Competition.one.show_bib_numbers?
      %td= entry.try(:entity).try(:bib_number)
    %td= entry.try(:entity).try(:last_name).to_s.truncate(20)
    %td= entry.try(:entity).try(:first_name).to_s.truncate(20)
    %td= entry.try(:entity).try(:team_shortcut_name, entry.try(:assessment_type)).to_s.truncate(20)
  - else
    %td
      = entry.try(:entity).try(:to_s, multiple_assessments?)
      - if multiple_assessments?
        %br
        .tiny= entry.try(:assessment).try(:decorate)
  = yield (track == 1)

app/views/score/lists/_list_headline.html.haml
%thead
  %tr{ class: "small" }
    %th Lauf
    %th Bahn
    - if single_discipline?
      - if Competition.one.show_bib_numbers?
        %th Nr.
      %th Nachname
      %th Vorname
    %th Mannschaft
    - if times
      %th Zeit

app/views/score/lists/_select_entity.html.haml
= box "Teilnehmer hinzufügen", modal: true do |box|
  = simple_form_for @score_list, remote: true do |f|
    - if not_yet_present_entities.count == 0
      .alert.alert-danger Es wurde alle möglichen Teilnehmer zugeordnet
    - else
      = f.error_notification
      - free_run, free_track = @score_list.next_free_track
      = f.simple_fields_for :entries, @score_list.entries.build(run: free_run, track: free_track, entity_type: discipline_klass.name) do |g|
        = g.association :entity, collection: not_yet_present_entities, label_method: lambda { |entity| label_method_for_select_entity(entity) }
        = g.input :run, as: :hidden
        = g.input :track, as: :hidden
        = g.input :entity_type, as: :hidden
        = g.association :assessment, collection: @score_list.assessments
        = g.input :assessment_type, as: :select, collection: AssessmentRequest.assessment_types.keys, label_method: lambda { |type| t("assessment_types.#{type}") }

        = "Wird in Lauf #{free_run} auf Bahn #{free_track} eingeordnet."
      .model-footer
        = f.primary_button :submit, "Hinzufügen"

app/views/score/lists/_tag_form.html.haml
- if @tags.present?
  %h3 Tags anzeigen
  - @tags.each do |tag|
    - if @score_list.tag_references.find {|tag_ref| tag_ref.tag_id == tag.id }.present?
      = f.simple_fields_for :tag_references, @score_list.tag_references.find {|tag_ref| tag_ref.tag_id == tag.id } do |g|
        = g.input :_destroy, as: :boolean, label: "#{tag.object.model_name.human} - #{tag.name}", input_html: { checked: true }, checked_value: "0", unchecked_value: "1"
        = g.input :tag_id, as: :hidden
    - else
      = f.simple_fields_for :tag_references, @score_list.tag_references.find_or_initialize_by(tag: tag) do |g|
        = g.input :_destroy, as: :boolean, label: "#{tag.object.model_name.human} - #{tag.name}", input_html: { checked: false }, checked_value: "0", unchecked_value: "1"
        = g.input :tag_id, as: :hidden
  .alert.alert-info
    %span.glyphicon.glyphicon-info-sign
    Wenn Sie hier einen oder mehrere Kennzeichnungen auswählen, werden auf diese auf der Startliste zusätzlich zum Namen angezeigt.

app/views/score/lists/destroy_entity.js.erb
Modals.push("<%= j render partial: 'destroy_entity' %>");

app/views/score/lists/edit_times.html.haml
.row
  .col-md-12
    = simple_form_for @score_list do |f|
      = box @score_list.name do |box|
        %table.table
          = render 'list_headline', times: true
          %tbody
            - score_list_entries do |entry, run, track|
              = render layout: 'list_entry', locals: { entry: entry, run: run, track: track } do
                = render 'score/runs/edit_time', entry: entry, f: f, fields_for: :entries
          - box.footer do
            = cancel_link
            = f.primary_button :submit, 'Speichern'

app/views/score/lists/index.html.haml
.row
  .col-md-8
    = box 'Startlisten' do |box|
      - if admin_logged_in?
        - box.header do
          .pull-right
            = btn_link_to "Hinzufügen", action: :new, controller: 'score/list_factories'
          .clearfix
      %table.table
        - @score_lists.each do |list|
          %tr
            %td
              = discipline_image(list.discipline)
              = list.name
            %td
              = btn_link_to "Ansehen", list
              - if logged_in? && !can?(:edit_times, list)
                %span.glyphicon.glyphicon-ban-circle

      - if admin_logged_in?
        - box.footer do
          = btn_link_to "Hinzufügen", action: :new, controller: 'score/list_factories'

  - if admin_logged_in? && @list_factory.present?
    .col-md-4
      = box 'Erstellungsvorgang' do |box|
        = block_link_to "Weiter mit Schritt #{@list_factory.current_step_number + 1}", edit_score_list_factories_path
        = block_link_to 'Abbrechen', score_list_factories_path, method: :delete, data: { confirm: 'Listenerstellung abbrechen?' }, class: 'btn btn-default btn-sm'

app/views/score/lists/move.html.haml
.row.refreshable#score-list-show
  .col-md-8
    = box @score_list.name do |box|
      %table.table.sorted_table{ data: { track_count: list_track_count } }
        = render 'list_headline', times: false
        %tbody
          - score_list_entries(true) do |entry, run, track|
            = render 'list_entry', entry: entry, run: run, track: track
          %tr.hide.placeholder
            %td{ colspan: 5 }
              %span
      - box.footer do
        = simple_form_for @score_list, html: { class: "hide score_list_form" } do |f|
          = cancel_link
          = f.primary_button :submit, "Liste speichern"
        
  .col-md-4
    = box("Hinweise") do
      %p Einfach die Zeilen in die neue Position ziehen. Danach unter der Tabelle auf Speichern klicken.
  .col-md-4
    = box("Aktionen") do
      = block_link_to "Ansehen", { action: :show }
      = block_link_to "Bearbeiten", { action: :edit }
      = block_link_to "Excel-Liste", { action: :show, format: :xlsx }

app/views/score/lists/select_entity.js.erb
Modals.push("<%= j render partial: 'select_entity' %>");

app/views/score/lists/show.html.haml
.row.refreshable#score-list-show
  .col-md-9
    = box @score_list.name do |box|
      %table.table
        = render 'list_headline', times: true
        %tbody
          - score_list_entries do |entry, run, track|
            = render layout: 'list_entry', locals: { entry: entry, run: run, track: track } do |first|
              %td.time-col
                = entry.try(:human_time)
                - if logged_in? && can?(:edit_times, @score_list)
                  .pull-right
                    - if track == 1
                      = short_edit_link edit_score_list_run_path(@score_list, run: run), title: 'Zeiten bearbeiten', class: 'btn-xs'
                    - if entry.present?
                      = short_destroy_link destroy_entity_score_list_path(@score_list, entry_id: entry.id), title: 'Aus Liste entfernen', class: 'btn-xs', remote: true
      - box.footer do
        = btn_link_to 'als PDF', format: :pdf
        = btn_link_to 'als PDF mit vorgetäuschtem zweiten Lauf', format: :pdf, double_run: true
        = btn_link_to 'als PDF für Kampfrichter', format: :pdf, more_columns: true
        = btn_link_to 'als XLS', format: :xlsx

  .col-md-3
    - if logged_in?
      = box('Aktionen') do
        - if can?(:edit, @score_list)
          = block_link_to 'Reihenfolge bearbeiten', { action: :move }
        - if can?(:edit_times, @score_list)
          = block_link_to 'Zeiten im Block eintragen', { action: :edit_times }
        - if can?(:edit, @score_list)
          = block_link_to 'Teilnehmer hinzufügen', { action: :select_entity }, remote: true

      - if can?(:edit, @score_list)
        = box('Allgemein') do
          = block_link_to 'Bearbeiten', { action: :edit }
          = block_link_to 'Löschen', { action: :destroy }, method: :delete, data: { confirm: 'Startliste wirklich löschen? Alle bisher eingetragenen Zeiten dieser Liste gehen verloren!' }

      = box('Ausgabe') do
        = block_link_to('PDF (Drucken)', format: :pdf)
        = block_link_to('PDF für Kampfrichter', format: :pdf, more_columns: true)
        = block_link_to('XLS (Excel)', format: :xlsx)